apiVersion: v1
kind: Service
metadata:
  name: zk-metrics
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: http-metrics
  selector:
    app: {{ template "zookeeper.name" . }}
    release: "{{ .Release.Name }}"